### ISSUE TITLE
About c standard

### ISSUE THREAD

**Issue by alex-rass-88** [tylov/C99Containers#1]
cfmt uses _Generic. This is C11 standard. In compilers without c11 support, the application will not build.

**Comment by tylov** [comment]
Thanks for reminding me. cfmt.h is an independent functionality only requires a few macros from ccommon.h. Will move it out of the lib and revert examples.

**Comment by tylov** [comment]
cfmt.h is now taken out of the library and moved to a gist: https://gist.github.com/tylov/bcc956a4779f1d14204e66a14f17beb9

All examples are reverted/updated to use printf() instead.
